apiVersion: apps/v1
kind: Deployment
metadata:
  name: BiddingParticipation
  labels:
    app: BiddingParticipation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BiddingParticipation
  template:
    metadata:
      labels:
        app: BiddingParticipation
    spec:
      containers:
        - name: BiddingParticipation
          image: username/BiddingParticipation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5