apiVersion: v1
kind: Service
metadata:
  name: BiddingParticipation
  labels:
    app: BiddingParticipation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BiddingParticipation